### ISSUE TITLE
Support for merging .pot file into .po file

### ISSUE THREAD

**Issue by atimmer** [blazersix/grunt-wp-i18n#45]
#39 talks about being able to create a new .po file from the .pot file, but after that has happened and you add new strings you want to merge the .pot file into the .po file. Currently I use poedit for this, but this is cumbersome at times.

The gettext command msgmerge can be used to achieve this behaviour. I found this gist that basically does what I want: https://gist.github.com/ccprog/12c10d6e611882ff2fc2

My main question is, is this something you want to provide in this grunt plugin, or is this out of scope? If so, I could provide a pull request to add this task.

**Comment by atimmer** [comment]
I made a pull request that is a very small wrapper around msgmerge --update.

We can solve both cases using this task. Do you think it is a good idea to have it in a separate task or should it somehow be a 'private' function.

**Comment by bradyvercher** [comment]
Nice work, @atimmer! I'm not too keen on exposing a new task, though, so I'm thinking the functionality could be wrapped up in a module in the `/tasks/lib` directory and a new option can be added to the `makepot` task to enable it (something like `updatePoFiles: true`), but I'm open to suggestions.

**Comment by atimmer** [comment]
I updated the pull request with the suggestions. `updatePoFiles` is a great idea, currently it is off by default. Tell me if you want it on by default. msgMerge is moved to `/tasks/lib`.

When makepo is implemented it can make use of msgMerge.

If this is the correct direction I will add some documentation to the pull request.

**Comment by bradyvercher** [comment]
This looks great. Off by default is good since that option requires an external dependency.

When you add the docs, [this section](https://github.com/atimmer/grunt-wp-i18n/commit/0e759a200b334e10774d02de755926c62fc33aa9#diff-a64f72ea0916f1c0f27fc69e3d06c82cR162) could use a few spaces to match the WP JS coding standards. Let me know when you get everything wrapped up and I'll do some testing and merge this.

Thanks a ton!

**Comment by atimmer** [comment]
The pull request should be done now. I've added some documentation and support for themes, because the PO files format is different for them.

**Comment by bradyvercher** [comment]
I left some comments on a couple of the commits for issues I noticed after pulling this down and giving it a quick run through. Once those are addressed, I think this should be good to go.

**Comment by atimmer** [comment]
They should all be fixed now, I actually got the backup files as well but my editor doesn't show them.

**Comment by bradyvercher** [comment]
Looks good! Once last thing, can you squash these commits? I'll merge it after that.

**Comment by atimmer** [comment]
Squashed.

**Comment by bradyvercher** [comment]
Merged. I'll run a few more tests and try to push out an update soon. Thanks again!

**Comment by GaryJones** [comment]
I'm seeing the tests fail with this

~~~sh
  Testing makepot_test.js..........F.F.
>> makepot - msg_merge_merging
>> Message: "Colors" string should exist
>> Error: undefined == true
>> at Object.exports.makepot.msg_merge_merging (test/makepot_test.js:173:8)
>> at Object.exports.makepot.setUp (test/makepot_test.js:28:3)

>> makepot - msg_merge_merging
>> Message: "Colors" string should exist
>> Error: undefined == true
>> at Object.exports.makepot.msg_merge_merging (test/makepot_test.js:174:8)
>> at Object.exports.makepot.setUp (test/makepot_test.js:28:3)

>> makepot - msg_merge_merging
>> Error: Expected 4 assertions, 2 ran
>> at processImmediate [as _immediateCallback] (timers.js:358:17)

>> makepot - msg_merge_merging
>> TypeError: Cannot read property 'comments' of undefined
>> at Object.exports.makepot.msg_merge_merging (test/makepot_test.js:176:47)
>> at Object.exports.makepot.setUp (test/makepot_test.js:28:3)

>> makepot - msg_merge_theme
>> Message: "Analog string should not exist
>> Error: false == true
>> at Object.exports.makepot.msg_merge_theme (test/makepot_test.js:205:8)
>> at Object.exports.makepot.setUp (test/makepot_test.js:28:3)

>> makepot - msg_merge_theme
>> Message: "Digital" string should exist
>> Error: undefined == true
>> at Object.exports.makepot.msg_merge_theme (test/makepot_test.js:206:8)
>> at Object.exports.makepot.setUp (test/makepot_test.js:28:3)

Warning: 6/59 assertions failed
~~~

(Also appears to be missing a double quote in one of the error message strings).

**Comment by bradyvercher** [comment]
I took a look into excluding those tests if msgmerge isn't available, but there doesn't appear to be a good way to detect whether or not an executable exists or to skip tests.

The one thing I can think of is to split the tests and add a flag to skip the ones that depend on msgmerge. Anyone have a better idea?

**Comment by atimmer** [comment]
To check if gettext is available thought of two approaches:
* Add a `isGettextAvailable` function to the util file that calls `gettext --version` and catches the error gracefully.
* This: https://github.com/arturadib/shelljs and then call `which( 'msgmerge' )` to check for the command.

**Comment by GaryJones** [comment]
Relevant (but old): https://github.com/caolan/nodeunit/issues/12

**Comment by shivapoudel** [comment]
Very easy, just be smart ;)

You can use `shelljs` for checking if `msgmerge` is found in system PATH or not.
https://github.com/axisthemes/grunt-potomo/blob/master/tasks/potomo.js#L20-L23

The `shelljs` module `which()`  is prepared to deal with `command` in the system's PATH:
https://github.com/arturadib/shelljs/blob/master/src/which.js#L33-L82

As I said, just be smart ;)
